/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedFlagsQuizRouteImport } from './routes/red-flags-quiz'
import { Route as LtvCacCalculatorRouteImport } from './routes/ltv-cac-calculator'
import { Route as CacPaybackCalculatorRouteImport } from './routes/cac-payback-calculator'
import { Route as IndexRouteImport } from './routes/index'

const RedFlagsQuizRoute = RedFlagsQuizRouteImport.update({
  id: '/red-flags-quiz',
  path: '/red-flags-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LtvCacCalculatorRoute = LtvCacCalculatorRouteImport.update({
  id: '/ltv-cac-calculator',
  path: '/ltv-cac-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CacPaybackCalculatorRoute = CacPaybackCalculatorRouteImport.update({
  id: '/cac-payback-calculator',
  path: '/cac-payback-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cac-payback-calculator': typeof CacPaybackCalculatorRoute
  '/ltv-cac-calculator': typeof LtvCacCalculatorRoute
  '/red-flags-quiz': typeof RedFlagsQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cac-payback-calculator': typeof CacPaybackCalculatorRoute
  '/ltv-cac-calculator': typeof LtvCacCalculatorRoute
  '/red-flags-quiz': typeof RedFlagsQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cac-payback-calculator': typeof CacPaybackCalculatorRoute
  '/ltv-cac-calculator': typeof LtvCacCalculatorRoute
  '/red-flags-quiz': typeof RedFlagsQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cac-payback-calculator' | '/ltv-cac-calculator' | '/red-flags-quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/cac-payback-calculator' | '/ltv-cac-calculator' | '/red-flags-quiz'
  id:
    | '__root__'
    | '/'
    | '/cac-payback-calculator'
    | '/ltv-cac-calculator'
    | '/red-flags-quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CacPaybackCalculatorRoute: typeof CacPaybackCalculatorRoute
  LtvCacCalculatorRoute: typeof LtvCacCalculatorRoute
  RedFlagsQuizRoute: typeof RedFlagsQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/red-flags-quiz': {
      id: '/red-flags-quiz'
      path: '/red-flags-quiz'
      fullPath: '/red-flags-quiz'
      preLoaderRoute: typeof RedFlagsQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ltv-cac-calculator': {
      id: '/ltv-cac-calculator'
      path: '/ltv-cac-calculator'
      fullPath: '/ltv-cac-calculator'
      preLoaderRoute: typeof LtvCacCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cac-payback-calculator': {
      id: '/cac-payback-calculator'
      path: '/cac-payback-calculator'
      fullPath: '/cac-payback-calculator'
      preLoaderRoute: typeof CacPaybackCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CacPaybackCalculatorRoute: CacPaybackCalculatorRoute,
  LtvCacCalculatorRoute: LtvCacCalculatorRoute,
  RedFlagsQuizRoute: RedFlagsQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
